QuenchMarks/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint("core", __name__)


@core.route("/")
def index():
    return render_template("home.html")

QuenchMarks/reviews/views.py
from flask import abort, render_template, url_for, request, redirect, flash, Blueprint
from flask_login import current_user, login_required
from werkzeug import datastructures
from QuenchMarks import db
from QuenchMarks.models import Bottle, Review
from .forms import ReviewForm

reviews = Blueprint("reviews", __name__)

# DEBUGGING = SEE ALL REVIEWS

# CREATE A REVIEW
@reviews.route("/bottles/<int:id>/addreview", methods=["GET", "POST"])
@login_required
def create_review(id):

    form = ReviewForm()

    if form.validate_on_submit():
        review = Review(
            rating = form.rating.data,
            text = form.text.data,
            author = current_user.id,
            bottle_id = Bottle.query.filter_by(id=id).first_or_404().id
        )
        db.session.add(review)
        db.session.commit()
        flash("Review Created")
        return redirect(url_for("bottles.bottle_detail", id=id))
    return render_template("reviews/input_review.html", form=form)

# UPDATE A REVIEW
@reviews.route("/updatereview/<int:id>", methods=["GET", "POST"])
@login_required
def update_review(id):

    review = Review.query.get_or_404(id)
    form = ReviewForm()

    if current_user.id != review.author.id:
        abort(403)

    if form.validate_on_submit():
        review.rating = form.rating.data
        review.text = form.text.data
        db.session.commit()
        flash("Review Created")
        return redirect(url_for("bottles.index"))
    return render_template("reviews/input_review.html", form=form)

# DELETE A REVIEW
@reviews.route("/deletereview/<int:id>", methods=["GET", "POST"])
@login_required
def delete_review(id):
    review = Review.query.get_or_404(id)
    bottle_id = review.bottle_id
    if current_user.id == review.author:
        db.session.delete(review)
        db.session.commit()
    else:
        abort(403)
    return redirect(url_for("bottles.bottle_detail", id=bottle_id))

QuenchMarks/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from QuenchMarks import db
from QuenchMarks.models import User, Bottle, user_favorites
from QuenchMarks.users.forms import RegistrationForm,LoginForm,UpdateUserForm

users = Blueprint('users',__name__)

# register
@users.route('/register', methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('Logged in successfully!')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route("/<username>")
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user_profile.html',user=user)

# favorite a bottle
@users.route("/<int:user_id>/add_fave/<int:bottle_id>", methods=['GET','POST'])
@login_required
def add_fave(user_id, bottle_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    user.favorites.append(Bottle.query.get(bottle_id))
    db.session.commit()
    print(user.favorites)
    return redirect(url_for('bottles.bottle_detail', id=bottle_id))

# UNfavorite a bottle
@users.route("/<int:user_id>/remove_fave/<int:bottle_id>", methods=['GET','POST'])
@login_required
def remove_fave(user_id, bottle_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    user.favorites.remove(Bottle.query.get(bottle_id))
    db.session.commit()
    return redirect(url_for('bottles.bottle_detail', id=bottle_id))

QuenchMarks/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/bulma.css') }}"
        />
        <link
        rel="stylesheet"
        href="{{ url_for('static', filename='css/styles.css') }}"
    />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css" integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />
        <title>QuenchMarks</title>
    </head>
    <body>
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href=""> QuenchMarks </a>

                <a
                    role="button"
                    class="navbar-burger"
                    aria-label="menu"
                    aria-expanded="false"
                    data-target="navbarBasicExample"
                >
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="{{url_for('core.index')}}">
                        Home
                    </a>
                    <a class="navbar-item" href="{{url_for('bottles.index')}}">
                        All Bottles
                    </a>
                    {% if current_user.is_authenticated %}
                    <a class="navbar-item" href="{{url_for('users.user_profile', username=current_user.username)}}">
                        My Profile
                    </a>
                    {% endif %}
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            {% if current_user.is_authenticated %}
                            <a
                                href="{{url_for('users.logout')}}"
                                class="button is-primary"
                            >
                                <strong>Log Out</strong>
                            </a>
                            {% else %}
                            <a
                                href="{{url_for('users.register')}}"
                                class="button is-primary"
                            >
                                <strong>Sign up</strong>
                            </a>
                            <a
                                href="{{url_for('users.login')}}"
                                class="button is-light"
                            >
                                Log in
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <div>{% block content %}</div>
        {% endblock %}
        <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    </body>
</html>

QuenchMarks/templates/home.html
{% extends 'base.html' %} {% block content%}
<section class="hero is-primary is-fullheight">
    <div class="hero-body">
      <div class="">
        <p class="title">
          QuenchMarks
        </p>
        <p class="subtitle">
        A Drinking Vessel Review Site built with Flask
        </p>
      </div>
    </div>
  </section>
{% endblock %}

QuenchMarks/templates/login.html
{% extends "base.html" %} {% block content %}
<section class="hero is-primary is-fullheight">
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="column is-4 is-offset-4">
                <h3 class="title has-text-black">Login</h3>
                <hr />
                <p class="subtitle has-text-black">Please login to proceed.</p>
                <div class="box">
                    <form method="POST">
                        {{form.hidden_tag()}}
                        <div class="field">
                            <div class="control">
                                {{form.email( class="input", placeholder="Your Email" )}}
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                {{form.password( class="input",
                                placeholder="Your Password" )}}
                            </div>
                        </div>
                        <button
                            class="button is-block is-primary is-large is-fullwidth"
                        >
                            Login
                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

QuenchMarks/templates/register.html
{% extends "base.html" %} {% block content %}
<section class="hero is-primary is-fullheight">
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="column is-4 is-offset-4">
                <h3 class="title has-text-black">Sign Up</h3>
                <hr />
                <p class="subtitle has-text-black">Sign Up to join our community</p>
                <div class="box">
                    <form method="POST">
                        {{form.hidden_tag()}}
                        <div class="field">
                            <div class="control">
                                {{form.email( class="input", placeholder="Your Email" )}}
                            </div>
                        </div>
                        <div class="field">
                            <div class="control">
                                {{form.username( class="input", placeholder="Your Username" )}}
                            </div>
                        </div>
                        
                        <div class="field">
                            <div class="control">
                                {{form.password( class="input",
                                placeholder="Your Password" )}}
                            </div>
                        </div>
                        <div class="field">
                            <div class="control">
                                {{form.pass_confirm( class="input",
                                placeholder="Confirm Password" )}}
                            </div>
                        </div>
                        <button
                            class="button is-block is-primary is-large is-fullwidth"
                        >
                            Register
                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

QuenchMarks/templates/user_profile.html
{% extends "base.html" %} {% block content %}
<div class="content">
    <h1>{{user.username}}</h1>
    <h2>Reviews by this user:</h2>
    <div class="container">
        <div class="columns is-multiline">
            {% for review in user.reviews %}
            <div class="column is-one-third">
                <div class="card">
                    <div class="card-content">
                        <p class="title is-4 has-text-centered">
                            Rating: {{review.rating}} Stars
                        </p>
                    </div>
                    <div class="content">
                        <p>{{review.text}}</p>
                        <br />
                        <time
                            >Review published: {{review.published.date()}}</time
                        >
                        <div class="card-footer">
                            <a
                                class="card-footer-item"
                                href="{{url_for('bottles.bottle_detail', id=review.bottle.id)}}"
                                >For: {{review.bottle.name}}</a
                            >
                            {% if current_user.username == review.user.username
                            %}
                            <a
                                class="card-footer-item has-text-danger"
                                href="{{url_for('reviews.delete_review', id=review.id)}}"
                                >delete</a
                            >
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <h2>{{user.username}}'s Favorite Bottles</h2>
    <ul>
        {% for bottle in user.favorites %}
        <li>
            <a href="{{url_for('bottles.bottle_detail', id=bottle.id)}}"
                >{{bottle.name}}</a
            >
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}