QuenchMarks/bottles/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BottlePostForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    brand = StringField("Brand", validators=[DataRequired()])
    material = StringField("Material", validators=[DataRequired()])
    volume = IntegerField("Volume (mL)", validators=[DataRequired()])
    submit = SubmitField("Post")


class BottleUpdateForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    brand = StringField("Brand", validators=[DataRequired()])
    material = StringField("Material", validators=[DataRequired()])
    volume = IntegerField("Volume (mL)", validators=[DataRequired()])
    submit = SubmitField("Update Info")

QuenchMarks/bottles/views.py
from cgitb import text
from flask import render_template, url_for, request, redirect, flash, Blueprint
from flask_login import current_user, login_required
from QuenchMarks import db
from QuenchMarks.models import Bottle, Review
from QuenchMarks.bottles.forms import BottlePostForm, BottleUpdateForm

bottles = Blueprint("bottles", __name__)


# INDEX BOTTLES
@bottles.route("/bottles/")
def index():
    bottles = Bottle.query.order_by(Bottle.name.asc()).all()
    return render_template("bottles/bottle_index.html", bottles=bottles)


@bottles.route("/bottles/<int:id>")
def bottle_detail(id):
    bottle = Bottle.query.filter_by(id=id).first_or_404()
    reviews = Review.query.filter_by(bottle_id=id)
    return render_template(
        "bottles/bottle_detail.html", bottle=bottle, reviews=reviews
    )


# CRUD FOR BOTTLES


# CREATE A BOTTLE
@bottles.route("/bottles/create", methods=["GET", "POST"])
@login_required
def create_bottle():
    form = BottlePostForm()
    if form.validate_on_submit():
        print(form)
        new_bottle = Bottle(
            name=form.name.data,
            brand=form.brand.data,
            material=form.material.data,
            volume=form.volume.data,
            posted_by=current_user.username,
        )
        db.session.add(new_bottle)
        db.session.commit()
        flash("Bottle Created")
        return redirect(url_for("bottles.index"))
    return render_template("bottles/create_bottle.html", form=form)


# UPDATE A BOTTLE INFO
@bottles.route("/bottles/<int:id>/update", methods=["GET", "POST"])
@login_required
def update_bottle(id):
    # get bottle
    bottle = Bottle.query.get_or_404(id)
    if current_user.username == bottle.posted_by:
        # pre-populate edit form
        updateForm = BottleUpdateForm()
        updateForm.name.data = bottle.name
        updateForm.brand.data = bottle.brand
        updateForm.material.data = bottle.material
        updateForm.volume.data = bottle.volume

        if updateForm.validate_on_submit():
            bottle.name = updateForm.name.data
            bottle.brand = updateForm.brand.data
            bottle.material = updateForm.material.data.lower()
            bottle.volume = updateForm.volume.data
            db.session.commit()
        return redirect(url_for("bottles.index"))
    else:
        return redirect(url_for("bottles.index"))
    return render_template("bottles/edit_bottle.html", form=updateForm, bottle=bottle)


# DELETE A BOTTLE
@bottles.route("/bottles/<int:id>/delete", methods=["GET", "POST"])
@login_required
def delete_bottle(id):
    if current_user.username == bottle.posted_by:
        bottle = Bottle.query.get_or_404(id)
        db.session.delete(bottle)
        db.session.commit()
        return redirect(url_for("bottles.index"))
    else:
        return redirect(url_for("bottles.index"))

QuenchMarks/reviews/views.py
from flask import abort, render_template, url_for, request, redirect, flash, Blueprint
from flask_login import current_user, login_required
from werkzeug import datastructures
from QuenchMarks import db
from QuenchMarks.models import Bottle, Review
from .forms import ReviewForm

reviews = Blueprint("reviews", __name__)

# DEBUGGING = SEE ALL REVIEWS

# CREATE A REVIEW
@reviews.route("/bottles/<int:id>/addreview", methods=["GET", "POST"])
@login_required
def create_review(id):

    form = ReviewForm()

    if form.validate_on_submit():
        review = Review(
            rating = form.rating.data,
            text = form.text.data,
            author = current_user.id,
            bottle_id = Bottle.query.filter_by(id=id).first_or_404().id
        )
        db.session.add(review)
        db.session.commit()
        flash("Review Created")
        return redirect(url_for("bottles.bottle_detail", id=id))
    return render_template("reviews/input_review.html", form=form)

# UPDATE A REVIEW
@reviews.route("/updatereview/<int:id>", methods=["GET", "POST"])
@login_required
def update_review(id):

    review = Review.query.get_or_404(id)
    form = ReviewForm()

    if current_user.id != review.author.id:
        abort(403)

    if form.validate_on_submit():
        review.rating = form.rating.data
        review.text = form.text.data
        db.session.commit()
        flash("Review Created")
        return redirect(url_for("bottles.index"))
    return render_template("reviews/input_review.html", form=form)

# DELETE A REVIEW
@reviews.route("/deletereview/<int:id>", methods=["GET", "POST"])
@login_required
def delete_review(id):
    review = Review.query.get_or_404(id)
    bottle_id = review.bottle_id
    if current_user.id == review.author:
        db.session.delete(review)
        db.session.commit()
    else:
        abort(403)
    return redirect(url_for("bottles.bottle_detail", id=bottle_id))

QuenchMarks/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from QuenchMarks import db
from QuenchMarks.models import User, Bottle, user_favorites
from QuenchMarks.users.forms import RegistrationForm,LoginForm,UpdateUserForm

users = Blueprint('users',__name__)

# register
@users.route('/register', methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('Logged in successfully!')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route("/<username>")
def user_profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user_profile.html',user=user)

# favorite a bottle
@users.route("/<int:user_id>/add_fave/<int:bottle_id>", methods=['GET','POST'])
@login_required
def add_fave(user_id, bottle_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    user.favorites.append(Bottle.query.get(bottle_id))
    db.session.commit()
    print(user.favorites)
    return redirect(url_for('bottles.bottle_detail', id=bottle_id))

# UNfavorite a bottle
@users.route("/<int:user_id>/remove_fave/<int:bottle_id>", methods=['GET','POST'])
@login_required
def remove_fave(user_id, bottle_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    user.favorites.remove(Bottle.query.get(bottle_id))
    db.session.commit()
    return redirect(url_for('bottles.bottle_detail', id=bottle_id))

QuenchMarks/templates/bottles/bottle_detail.html
{% extends "base.html" %} {% block content %}
<div class="content">
    <h1>Bottle Profile: {{bottle.name}}</h1>
    <table class="is-table">
        <tr>
            <td>Brand:</td>
            <td>{{bottle.brand}}</td>
        </tr>
        <tr>
            <td>Material:</td>
            <td>{{bottle.material}}</td>
        </tr>
        <tr>
            <td>Capacity:</td>
            <td>{{bottle.volume / 1000}} L</td>
        </tr>
    </table>
    <h2 class="has-text-centered">Reviews</h2>
    <br />
    <div class="container">
        <div class="columns is-multiline">
            {% for review in reviews %}
            <div class="column is-one-third m-1">
                <div class="card">
                    <div class="card-content">
                        <p class="title is-4 has-text-centered">
                            Rating: {{review.rating}} Stars
                        </p>
                    </div>
                    <div class="content">
                        <p>{{review.text}}</p>
                        <br />
                        <time
                            >Review published: {{review.published.date()}}</time
                        >
                        <div class="card-footer">
                            <a
                                class="card-footer-item"
                                href="{{url_for('users.user_profile', username=review.user.username)}}"
                                >{{review.user.username}}</a
                            >
                            {% if current_user.username == review.user.username
                            %}
                            <a
                                class="card-footer-item has-text-danger"
                                href="{{url_for('reviews.delete_review', id=review.id)}}"
                                >delete</a
                            >
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br />
    <div class="has-text-centered">
        <a href="{{url_for('reviews.create_review', id=bottle.id)}}"
            ><button class="button is-primary">add a review</button></a
        >
        {% if current_user.is_authenticated %} {% if bottle in
        current_user.favorites %}
        <a
            href="{{url_for('users.remove_fave', user_id=current_user.id, bottle_id=bottle.id)}}"
            ><button class="button is-warning">
                Unfavorite this bottle
            </button></a
        >
        {% else %}
        <a
            href="{{url_for('users.add_fave', user_id=current_user.id, bottle_id=bottle.id)}}"
            ><button class="button is-info">Favorite this bottle</button></a
        >
        {% endif %} {% endif %}
    </div>
</div>
{% endblock %}

QuenchMarks/templates/bottles/bottle_index.html
{% extends "base.html" %} {% block content %}
<div class="content">
    <h1>All Bottles</h1>
    <table class="table is-narrow is-striped">
        <thead>
            <tr>
                <th>Bottle Name</th>
                <th>Brand</th>
                <th>Material</th>
                <th>Volume (L)</th>
                <th>Posted By:</th>
            </tr>
        </thead>
        <tbody>
            {% for bottle in bottles %}
            <tr>
                <td> <a href="{{url_for('bottles.bottle_detail', id=bottle.id)}}">{{bottle.name}}</a></td>
                <td>{{bottle.brand}}</td>
                <td>{{bottle.material}}</td>
                <td>{{bottle.volume / 1000}}</td>
                <td>{{bottle.posted_by}}</td>
                {% if current_user.username == bottle.posted_by %}
                <td><a href="{{url_for('bottles.update_bottle', id=bottle.id)}}"><span class="tag is-link">Edit</span></a></td>
                <td><a href="{{url_for('bottles.delete_bottle', id=bottle.id)}}"><span class="tag is-danger">Delete</span><a></td>
                {% endif %}
            </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{{url_for('bottles.create_bottle')}}"><button class="button is-primary">add a new bottle</button></a>
    </div>
    {% endblock %}

QuenchMarks/templates/bottles/create_bottle.html
{% extends "base.html" %} {% block content %}
<div class="column is-half">
    <h1>Add A Bottle</h1>
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="field">
            {{form.name.label(class="label")}} {{form.name(class="input")}}
        </div>
        <div class="field">
            {{form.brand.label(class="label")}} {{form.brand(class="input")}}
        </div>
        <div class="field">
            {{form.material.label(class="label")}}
            {{form.material(class="input")}}
        </div>
        <div class="field">
            {{form.volume.label(class="label")}} {{form.volume(class="input")}}
        </div>
        <div class="field">{{form.submit(class="button is-primary")}}</div>
    </form>
</div>
{% endblock %}

QuenchMarks/templates/bottles/edit_bottle.html
{% extends "base.html" %} {% block content %}
<div class="column">
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="field">
            {{form.name.label(class="label")}} {{form.name(class="input")}}
        </div>
        <div>
            {{form.brand.label(class="label")}} {{form.brand(class="input")}}
        </div>
        <div class="field">
            {{form.material.label(class="label")}}
            {{form.material(class="input")}}
        </div>
        <div class="field">
            {{form.volume.label(class="label")}} {{form.volume(class="input")}}
        </div>
        <div class="field">{{form.submit(class="button is-primary")}}</div>
    </form>
</div>
{% endblock %}